language: python
os:
  - linux
#sudo: required
services:
  - redis-server
python:
#  - 2.7
  - 3.5
install:
  - pip install pytest
  - pip install flake8
  - pip install fake_rpi  
before_script:
  - pip install -r requirements.txt
  # stop the build if there are Python syntax errors
  # Ignore unused imports F401
  - flake8 . --count --select=E901,E999,F701,F702,F706,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - pytest
